name: Node CI

on:
    pull_request:
        types: [opened, reopened, edited]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 18x
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x
            - name: install yarn
              run: npm install -g yarn
            - run: yarn install  --frozen-lockfile
            - run: yarn build
            - run: yarn test
            - run: yarn danger ci
              env:
                  DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
